package com.project.ui;

public class InputForm extends javax.swing.JFrame {

    public InputForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        txtTitle = new javax.swing.JLabel();
        txtSubTitle = new javax.swing.JLabel();
        txtHomeClubName = new javax.swing.JLabel();
        cmbHomeClubName = new javax.swing.JComboBox<>();
        txtVisitorClubName = new javax.swing.JLabel();
        cmbVisitorClubName = new javax.swing.JComboBox<>();
        txtMatchTime = new javax.swing.JLabel();
        cmbMatchTime = new javax.swing.JComboBox<>();
        txtArriscar = new javax.swing.JLabel();
        sliderRisk = new javax.swing.JSlider();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        txtTitle.setFont(new java.awt.Font("Ubuntu Condensed", 1, 60)); // NOI18N
        txtTitle.setText("BetterBet");

        txtSubTitle.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        txtSubTitle.setForeground(new java.awt.Color(51, 102, 255));
        txtSubTitle.setText("a melhor plataforma de apostas");

        txtHomeClubName.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        txtHomeClubName.setText("Time mandante");

        cmbHomeClubName.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cmbHomeClubName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "America-RN", "Athletico-PR", "Atletico-MG", "Avai", "Bahia", "Botafogo-RJ", "Brasiliense", "Corinthians", "Coritiba", "Criciuma", "Cruzeiro", "Figueirense", "Flamengo", "Fluminense", "Fortaleza", "Goias", "Gremio", "Guarani", "Internacional", "Ipatinga", "Juventude", "Nautico", "Palmeiras", "Parana", "Paysandu", "Ponte Preta", "Portuguesa", "Santa Cruz", "Santos", "Sao Caetano", "Sao Paulo", "Sport", "Vasco", "Vitoria" }));
        cmbHomeClubName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbHomeClubName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHomeClubNameActionPerformed(evt);
            }
        });

        txtVisitorClubName.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        txtVisitorClubName.setText("Time visitante");

        cmbVisitorClubName.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cmbVisitorClubName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "America-RN", "Athletico-PR", "Atletico-MG", "Avai", "Bahia", "Botafogo-RJ", "Brasiliense", "Corinthians", "Coritiba", "Criciuma", "Cruzeiro", "Figueirense", "Flamengo", "Fluminense", "Fortaleza", "Goias", "Gremio", "Guarani", "Internacional", "Ipatinga", "Juventude", "Nautico", "Palmeiras", "Parana", "Paysandu", "Ponte Preta", "Portuguesa", "Santa Cruz", "Santos", "Sao Caetano", "Sao Paulo", "Sport", "Vasco", "Vitoria" }));
        cmbVisitorClubName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVisitorClubNameActionPerformed(evt);
            }
        });

        txtMatchTime.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        txtMatchTime.setText("Hora");

        cmbMatchTime.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cmbMatchTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "00:30", "01:00", "01:30", "02:00", "02:30", "03:00", "03:30", "04:00", "04:30", "05:00", "05:30", "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30" }));
        cmbMatchTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMatchTimeActionPerformed(evt);
            }
        });

        txtArriscar.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        txtArriscar.setText("Arriscar");

        sliderRisk.setForeground(new java.awt.Color(51, 102, 255));
        sliderRisk.setValue(85);

        btnEnviar.setBackground(new java.awt.Color(51, 102, 255));
        btnEnviar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Enviar");
        btnEnviar.setBorderPainted(false);
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtTitle)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHomeClubName)
                            .addComponent(cmbHomeClubName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtVisitorClubName)
                            .addComponent(cmbVisitorClubName, 0, 368, Short.MAX_VALUE)
                            .addComponent(txtMatchTime)
                            .addComponent(cmbMatchTime, 0, 368, Short.MAX_VALUE)
                            .addComponent(txtArriscar)
                            .addComponent(sliderRisk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(txtSubTitle))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btnEnviar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSubTitle)
                .addGap(38, 38, 38)
                .addComponent(txtHomeClubName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbHomeClubName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtVisitorClubName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbVisitorClubName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMatchTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbMatchTime, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtArriscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderRisk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void cmbHomeClubNameActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        String timeMandanteSelecionado = cmbHomeClubName.getSelectedItem().toString();
    }                                               

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String timeMandanteSelecionado = cmbHomeClubName.getSelectedItem().toString();
        String timeVisitanteSelecionado = cmbVisitorClubName.getSelectedItem().toString();
        String horarioSelecionado = cmbMatchTime.getSelectedItem().toString();
        int riscoSelecionado = sliderRisk.getValue();

        // Limpar os campos
        cmbHomeClubName.setSelectedIndex(0);
        cmbVisitorClubName.setSelectedIndex(0);
        cmbMatchTime.setSelectedIndex(0);
        sliderRisk.setValue(85);
        
    }                                         

    private void cmbVisitorClubNameActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void cmbMatchTimeActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnEnviar;
    private javax.swing.JComboBox<String> cmbHomeClubName;
    private javax.swing.JComboBox<String> cmbMatchTime;
    private javax.swing.JComboBox<String> cmbVisitorClubName;
    private javax.swing.JSlider sliderRisk;
    private javax.swing.JLabel txtArriscar;
    private javax.swing.JLabel txtHomeClubName;
    private javax.swing.JLabel txtMatchTime;
    private javax.swing.JLabel txtSubTitle;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JLabel txtVisitorClubName;
    // End of variables declaration                   
}
